<?php
/**
 * World Clock Class
 *
 * @package ToolZoo
 */

// Security: Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Toolzoo_Worldclock class
 *
 * Displays current time in 30 major cities around the world
 */
class Toolzoo_Worldclock {
    /**
     * Generate HTML output
     *
     * @return string HTML output
     */
    public function render() {
        // Enqueue CSS/JS
        $this->enqueue_assets();

        // Generate HTML
        ob_start();
        ?>
        <div class="toolzoo-worldclock-container" id="toolzoo-worldclock">
            <div class="toolzoo-worldclock-header">
                <h3><?php esc_html_e('World Clock', 'toolzoo'); ?></h3>
                <p class="toolzoo-worldclock-description">
                    <?php esc_html_e('Current time in 30 major cities around the world, sorted from your timezone eastward.', 'toolzoo'); ?>
                </p>
            </div>

            <div class="toolzoo-worldclock-list" id="toolzoo-worldclock-list">
                <!-- Dynamically generated by JavaScript -->
            </div>
        </div>
        <?php
        return ob_get_clean();
    }

    /**
     * Get cities list
     *
     * @return array Array of city information
     */
    private function get_cities_list() {
        return array(
            array(
                'city'     => __('London', 'toolzoo'),
                'country'  => __('United Kingdom', 'toolzoo'),
                'timezone' => 'Europe/London',
            ),
            array(
                'city'     => __('New York', 'toolzoo'),
                'country'  => __('United States', 'toolzoo'),
                'timezone' => 'America/New_York',
            ),
            array(
                'city'     => __('Paris', 'toolzoo'),
                'country'  => __('France', 'toolzoo'),
                'timezone' => 'Europe/Paris',
            ),
            array(
                'city'     => __('Singapore', 'toolzoo'),
                'country'  => __('Singapore', 'toolzoo'),
                'timezone' => 'Asia/Singapore',
            ),
            array(
                'city'     => __('Amsterdam', 'toolzoo'),
                'country'  => __('Netherlands', 'toolzoo'),
                'timezone' => 'Europe/Amsterdam',
            ),
            array(
                'city'     => __('Seoul', 'toolzoo'),
                'country'  => __('South Korea', 'toolzoo'),
                'timezone' => 'Asia/Seoul',
            ),
            array(
                'city'     => __('Tokyo', 'toolzoo'),
                'country'  => __('Japan', 'toolzoo'),
                'timezone' => 'Asia/Tokyo',
            ),
            array(
                'city'     => __('Dubai', 'toolzoo'),
                'country'  => __('United Arab Emirates', 'toolzoo'),
                'timezone' => 'Asia/Dubai',
            ),
            array(
                'city'     => __('Melbourne', 'toolzoo'),
                'country'  => __('Australia', 'toolzoo'),
                'timezone' => 'Australia/Melbourne',
            ),
            array(
                'city'     => __('Berlin', 'toolzoo'),
                'country'  => __('Germany', 'toolzoo'),
                'timezone' => 'Europe/Berlin',
            ),
            array(
                'city'     => __('Copenhagen', 'toolzoo'),
                'country'  => __('Denmark', 'toolzoo'),
                'timezone' => 'Europe/Copenhagen',
            ),
            array(
                'city'     => __('Sydney', 'toolzoo'),
                'country'  => __('Australia', 'toolzoo'),
                'timezone' => 'Australia/Sydney',
            ),
            array(
                'city'     => __('Vienna', 'toolzoo'),
                'country'  => __('Austria', 'toolzoo'),
                'timezone' => 'Europe/Vienna',
            ),
            array(
                'city'     => __('Madrid', 'toolzoo'),
                'country'  => __('Spain', 'toolzoo'),
                'timezone' => 'Europe/Madrid',
            ),
            array(
                'city'     => __('Shanghai', 'toolzoo'),
                'country'  => __('China', 'toolzoo'),
                'timezone' => 'Asia/Shanghai',
            ),
            array(
                'city'     => __('Stockholm', 'toolzoo'),
                'country'  => __('Sweden', 'toolzoo'),
                'timezone' => 'Europe/Stockholm',
            ),
            array(
                'city'     => __('Beijing', 'toolzoo'),
                'country'  => __('China', 'toolzoo'),
                'timezone' => 'Asia/Shanghai',
            ),
            array(
                'city'     => __('Hong Kong', 'toolzoo'),
                'country'  => __('China', 'toolzoo'),
                'timezone' => 'Asia/Hong_Kong',
            ),
            array(
                'city'     => __('Zurich', 'toolzoo'),
                'country'  => __('Switzerland', 'toolzoo'),
                'timezone' => 'Europe/Zurich',
            ),
            array(
                'city'     => __('Frankfurt', 'toolzoo'),
                'country'  => __('Germany', 'toolzoo'),
                'timezone' => 'Europe/Berlin',
            ),
            array(
                'city'     => __('Los Angeles', 'toolzoo'),
                'country'  => __('United States', 'toolzoo'),
                'timezone' => 'America/Los_Angeles',
            ),
            array(
                'city'     => __('Barcelona', 'toolzoo'),
                'country'  => __('Spain', 'toolzoo'),
                'timezone' => 'Europe/Madrid',
            ),
            array(
                'city'     => __('Toronto', 'toolzoo'),
                'country'  => __('Canada', 'toolzoo'),
                'timezone' => 'America/Toronto',
            ),
            array(
                'city'     => __('Brussels', 'toolzoo'),
                'country'  => __('Belgium', 'toolzoo'),
                'timezone' => 'Europe/Brussels',
            ),
            array(
                'city'     => __('Chicago', 'toolzoo'),
                'country'  => __('United States', 'toolzoo'),
                'timezone' => 'America/Chicago',
            ),
            array(
                'city'     => __('Geneva', 'toolzoo'),
                'country'  => __('Switzerland', 'toolzoo'),
                'timezone' => 'Europe/Zurich',
            ),
            array(
                'city'     => __('San Francisco', 'toolzoo'),
                'country'  => __('United States', 'toolzoo'),
                'timezone' => 'America/Los_Angeles',
            ),
            array(
                'city'     => __('Dublin', 'toolzoo'),
                'country'  => __('Ireland', 'toolzoo'),
                'timezone' => 'Europe/Dublin',
            ),
            array(
                'city'     => __('Boston', 'toolzoo'),
                'country'  => __('United States', 'toolzoo'),
                'timezone' => 'America/New_York',
            ),
            array(
                'city'     => __('Istanbul', 'toolzoo'),
                'country'  => __('Turkey', 'toolzoo'),
                'timezone' => 'Europe/Istanbul',
            ),
        );
    }

    /**
     * Enqueue CSS/JS
     */
    private function enqueue_assets() {
        // CSS
        wp_enqueue_style(
            'toolzoo-worldclock-css',
            TOOLZOO_PLUGIN_URL . 'assets/css/worldclock.css',
            array(),
            TOOLZOO_VERSION
        );

        // JavaScript
        wp_enqueue_script(
            'toolzoo-worldclock-js',
            TOOLZOO_PLUGIN_URL . 'assets/js/worldclock.js',
            array(),
            TOOLZOO_VERSION,
            true
        );

        // Pass cities data to JavaScript
        wp_localize_script(
            'toolzoo-worldclock-js',
            'toolzooWorldclockData',
            array(
                'cities' => $this->get_cities_list(),
                'labels' => array(
                    'currentTime' => __('Current Time:', 'toolzoo'),
                    'date'        => __('Date:', 'toolzoo'),
                    'yourLocation' => __('Your Location', 'toolzoo'),
                ),
            )
        );
    }
}
