<?php
/**
 * Japanese Era List Display Class
 *
 * @package ToolZoo
 */

// Security: Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Toolzoo_Nengo_List クラス
 */
class Toolzoo_Nengo_List {
    /**
     * Generate HTML output
     *
     * @return string HTML output
     */
    public function render() {
        // Enqueue CSS/JS
        $this->enqueue_assets();

        // Generate HTML
        ob_start();
        ?>
        <div class="toolzoo-nengo-container" id="toolzoo-nengo-list">
            <div class="toolzoo-nengo-header">
                <h3><?php esc_html_e('Japanese Era List', 'toolzoo'); ?></h3>
                <p class="toolzoo-nengo-description">
                    <?php
                    /* translators: %s: current year */
                    printf(
                        esc_html__('Displays Japanese era names and Western calendar years from 1868 (Meiji 1) to %s.', 'toolzoo'),
                        date('Y')
                    );
                    ?>
                </p>
            </div>

            <div class="toolzoo-nengo-jump-buttons">
                <button class="toolzoo-nengo-jump-btn" data-era="meiji"><?php esc_html_e('Meiji', 'toolzoo'); ?></button>
                <button class="toolzoo-nengo-jump-btn" data-era="taisho"><?php esc_html_e('Taisho', 'toolzoo'); ?></button>
                <button class="toolzoo-nengo-jump-btn" data-era="showa"><?php esc_html_e('Showa', 'toolzoo'); ?></button>
                <button class="toolzoo-nengo-jump-btn" data-era="heisei"><?php esc_html_e('Heisei', 'toolzoo'); ?></button>
                <button class="toolzoo-nengo-jump-btn" data-era="reiwa"><?php esc_html_e('Reiwa', 'toolzoo'); ?></button>
            </div>

            <div class="toolzoo-nengo-table-wrapper">
                <div id="toolzoo-nengo-table-container">
                    <!-- <?php esc_html_e('Dynamically generated by JavaScript', 'toolzoo'); ?> -->
                    <div class="toolzoo-loading"><?php esc_html_e('Loading data...', 'toolzoo'); ?></div>
                </div>
            </div>

            <div class="toolzoo-nengo-footer">
                <button id="toolzoo-scroll-top-btn" class="toolzoo-btn-secondary">
                    <?php esc_html_e('Back to Top', 'toolzoo'); ?>
                </button>
            </div>
        </div>
        <?php
        return ob_get_clean();
    }

    /**
     * Enqueue CSS/JS
     */
    private function enqueue_assets() {
        // CSS
        wp_enqueue_style(
            'toolzoo-nengo-css',
            TOOLZOO_PLUGIN_URL . 'assets/css/nengo.css',
            array(),
            TOOLZOO_VERSION
        );

        // JavaScript
        wp_enqueue_script(
            'toolzoo-nengo-js',
            TOOLZOO_PLUGIN_URL . 'assets/js/nengo.js',
            array(),
            TOOLZOO_VERSION,
            true
        );

        // Localize script for translations
        wp_localize_script(
            'toolzoo-nengo-js',
            'toolzooNengoL10n',
            array(
                'yearOne'         => __('Year 1', 'toolzoo'),
                'westernCalendar' => __('Western Calendar', 'toolzoo'),
                'meiji'           => __('Meiji', 'toolzoo'),
                'taisho'          => __('Taisho', 'toolzoo'),
                'showa'           => __('Showa', 'toolzoo'),
                'heisei'          => __('Heisei', 'toolzoo'),
                'reiwa'           => __('Reiwa', 'toolzoo'),
            )
        );
    }
}
