<?php
/**
 * Password Generator Class
 *
 * @package ToolZoo
 */

// Security: Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Toolzoo_Password_Generator クラス
 */
class Toolzoo_Password_Generator {
    /**
     * Generate HTML output
     *
     * @return string HTML output
     */
    public function render() {
        // Enqueue CSS/JS
        $this->enqueue_assets();

        // Generate HTML
        ob_start();
        ?>
        <div class="toolzoo-password-container" id="toolzoo-password-generator">
            <div class="toolzoo-password-header">
                <h3><?php esc_html_e('Password Generator', 'toolzoo'); ?></h3>
            </div>

            <div class="toolzoo-password-options">
                <div class="toolzoo-option-group">
                    <label for="toolzoo-password-length">
                        <?php esc_html_e('Length:', 'toolzoo'); ?> <span id="toolzoo-length-value">16</span> <?php esc_html_e('characters', 'toolzoo'); ?>
                    </label>
                    <input
                        type="range"
                        id="toolzoo-password-length"
                        class="toolzoo-password-slider"
                        min="8"
                        max="64"
                        value="16"
                        step="1"
                    >
                    <div class="toolzoo-slider-labels">
                        <span><?php esc_html_e('8 chars', 'toolzoo'); ?></span>
                        <span><?php esc_html_e('64 chars', 'toolzoo'); ?></span>
                    </div>
                </div>

                <div class="toolzoo-option-group">
                    <label class="toolzoo-checkbox-label">
                        <input
                            type="checkbox"
                            id="toolzoo-use-numbers"
                            class="toolzoo-char-type"
                            checked
                        >
                        <?php esc_html_e('Numbers (0-9)', 'toolzoo'); ?>
                    </label>
                    <label class="toolzoo-checkbox-label">
                        <input
                            type="checkbox"
                            id="toolzoo-use-lowercase"
                            class="toolzoo-char-type"
                            checked
                        >
                        <?php esc_html_e('Lowercase Letters (a-z)', 'toolzoo'); ?>
                    </label>
                    <label class="toolzoo-checkbox-label">
                        <input
                            type="checkbox"
                            id="toolzoo-use-uppercase"
                            class="toolzoo-char-type"
                            checked
                        >
                        <?php esc_html_e('Uppercase Letters (A-Z)', 'toolzoo'); ?>
                    </label>
                    <label class="toolzoo-checkbox-label">
                        <input
                            type="checkbox"
                            id="toolzoo-use-symbols"
                            class="toolzoo-char-type"
                            checked
                        >
                        <?php esc_html_e('Symbols (!@#$%^&*()_+-=[]{}|;:,.<?>&?)', 'toolzoo'); ?>
                    </label>
                    <label class="toolzoo-checkbox-label">
                        <input
                            type="checkbox"
                            id="toolzoo-exclude-ambiguous"
                            class="toolzoo-option-checkbox"
                        >
                        <?php esc_html_e('Exclude Ambiguous Characters (!|1lIiO0o, etc.)', 'toolzoo'); ?>
                    </label>
                </div>

                <div class="toolzoo-option-group">
                    <button
                        id="toolzoo-generate-btn"
                        class="toolzoo-btn toolzoo-btn-primary"
                    >
                        <?php esc_html_e('Generate Passwords (20)', 'toolzoo'); ?>
                    </button>
                </div>

                <div id="toolzoo-error-message" class="toolzoo-error" style="display: none;"></div>
            </div>

            <div class="toolzoo-password-results">
                <h4><?php esc_html_e('Generated Passwords', 'toolzoo'); ?></h4>
                <div id="toolzoo-password-list-container">
                    <!-- <?php esc_html_e('Dynamically generated by JavaScript', 'toolzoo'); ?> -->
                </div>
            </div>
        </div>
        <?php
        return ob_get_clean();
    }

    /**
     * Enqueue CSS/JS
     */
    private function enqueue_assets() {
        // CSS
        wp_enqueue_style(
            'toolzoo-password-css',
            TOOLZOO_PLUGIN_URL . 'assets/css/password.css',
            array(),
            TOOLZOO_VERSION
        );

        // JavaScript
        wp_enqueue_script(
            'toolzoo-password-js',
            TOOLZOO_PLUGIN_URL . 'assets/js/password.js',
            array(),
            TOOLZOO_VERSION,
            true
        );
    }
}
